"""initial migration

Revision ID: 56ef56dd73ad
Revises: 
Create Date: 2025-02-22 22:38:39.272272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56ef56dd73ad'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS core")
    op.create_table('product',
    sa.Column('product_key', sa.CHAR(length=32), nullable=False),
    sa.Column('create_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('update_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('record_effective_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('record_expiration_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('current_record_indicator', sa.CHAR(length=1), nullable=False),
    sa.Column('product_code', sa.String(length=255), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('product_description', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('product_key'),
    schema='core',
    comment='product table in core schema'
    )
    op.create_index('identify_product', 'product', ['product_key', 'current_record_indicator'], unique=False, schema='core')
    op.create_index('product_PK_index', 'product', ['product_key'], unique=False, schema='core')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('product_PK_index', table_name='product', schema='core')
    op.drop_index('identify_product', table_name='product', schema='core')
    op.drop_table('product', schema='core')
    op.execute("DROP SCHEMA IF EXISTS core")
    # ### end Alembic commands ###
